version: "3.9"

services:
  # -------------------------
  # Frontend dev
  # -------------------------
  rpg-card-creator-dev:
    image: node:22-slim
    working_dir: /nuxt-app
    volumes:
      - .:/nuxt-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    command: >
      bash -c "
        corepack enable &&
        corepack prepare pnpm@9.12.1 --activate &&
        pnpm install &&
        pnpm dev
      "
    restart: unless-stopped
